# Generated by Django 4.2 on 2024-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp_number',
            field=models.IntegerField(null=True),
        ),
    ]
