# Generated by Django 4.2 on 2024-12-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_registration_otp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ontimepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='otp_number',
        ),
    ]
