# Generated by Django 4.2 on 2024-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_ontimepassword_remove_registration_otp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontimepassword',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ontimepassword',
            name='stored_otp',
            field=models.IntegerField(null=True),
        ),
    ]
