# Generated by Django 4.2 on 2024-12-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_ontimepassword_email_ontimepassword_stored_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontimepassword',
            name='stored_otp',
        ),
        migrations.AddField(
            model_name='ontimepassword',
            name='otp_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ontimepassword',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
