# Generated by Django 4.2 on 2024-12-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_ontimepassword_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ontimepassword',
            name='otp_user',
        ),
    ]
