# Generated by Django 4.2 on 2024-12-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_ontimepassword_email_ontimepassword_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
